# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUqjp_Ebt6Uh0y7oCef4j8E_HIyuk7px
"""

import streamlit as st
st.title('IMDB movie review sentiment analysis')
st.write('enter a movie review to classify it as a positive or negative review')
user_input = st.text_area('movie review')
if st.button('classify'):
  preprocessed_input=preprocess_text(user_input)
  sentiment= 'positive' if model.predict(preprocessed_input)[0][0] > 0.5 else 'negative'
  st.write(f'sentiment: {sentiment}')
  st.write(f'prediction score: {model.predict(preprocessed_input)[0][0]}')
else:
    st.write('please enter a movie review')
